---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparklms-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparklms
  template:
    metadata:
      labels:
        app: sparklms
    spec:
      containers:
        - name: sparklms
          image: saminbjit/sparklms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: website-data
              mountPath: /tmp
      volumes:
        - name: website-data
          persistentVolumeClaim:
            claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sparklms-service
spec:
  type: NodePort
  selector:
    app: sparklms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/website-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: app-pv
  storageClassName: standard
